//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTestLog
    {
        public int AutoTestLogID { get; set; }
        public Nullable<int> AutoTestID { get; set; }
        public string TestName { get; set; }
        public string TestStatus { get; set; }
        public Nullable<System.DateTime> TestedTime { get; set; }
    }
}
