//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int TaskID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<System.DateTime> StartTimezone { get; set; }
        public Nullable<System.DateTime> EndTimezone { get; set; }
        public string Description { get; set; }
        public Nullable<int> RecurrenceID { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceException { get; set; }
        public Nullable<bool> IsAllDay { get; set; }
    }
}
