//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseLogDataFreshness
    {
        public int TestCaseLogDataFreshnessId { get; set; }
        public Nullable<int> TestCaseLogId { get; set; }
        public Nullable<int> TestInstanceId { get; set; }
        public Nullable<int> TestCaseId { get; set; }
        public Nullable<long> SourceDate { get; set; }
        public Nullable<long> DestinationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
