//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseParameterQvtValidation
    {
        public int TestCaseParameterQvtValidationId { get; set; }
        public int TestCaseId { get; set; }
        public string ExcelFile { get; set; }
        public string TempTable { get; set; }
        public string ValidationStoredProc { get; set; }
        public string StoredProcArg1 { get; set; }
        public string StoredProcArg2 { get; set; }
        public string StoredProcArg3 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
