//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCase
    {
        public int TestCaseId { get; set; }
        public int TestSuiteId { get; set; }
        public int PipelineStageId { get; set; }
        public int TestCaseTypeId { get; set; }
        public string TestCaseName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsObsolete { get; set; }
        public string ObsoleteReason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual PipelineStage PipelineStage { get; set; }
        public virtual TestCaseType TestCaseType { get; set; }
        public virtual TestSuite TestSuite { get; set; }
    }
}
