//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseParameterRowCount
    {
        public int TestCaseParameterRowCountId { get; set; }
        public int TestCaseId { get; set; }
        public string TableName { get; set; }
        public string SourceFilePath { get; set; }
        public string DestinationFilePath { get; set; }
        public Nullable<short> FileColumnsCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
