//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseParametersForQvtValidationAssociatedTable
    {
        public int TestCaseParametersForQvtValidationAssociatedTableId { get; set; }
        public int TestCaseParameterQvtValidationExceptionId { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
